version: '3'
services:
  cinemaster:
    build: ./
    container_name: cinemaster-frontend
    ports:
      - 4200:80
    networks:
      - cinemaster_net
networks:
  cinemaster_net:
    driver: bridge